---
#- name: Add "ClamAV Sylog Event" marker cron job
#  cron:
#    name: "ClamAV Syslog Event"
#    minute: "30"
#    hour: "22"
#    job: logger -i -t clamav -p local2.info "Starting ClamAV scan"
#    backup: yes
#  register: backup_file

- name: Add "ClamAV Scan" cron job
  cron:
    name: "ClamAV Scan"
    minute: "30"
    hour: "22"
    weekday: 1,4
    job: clamscan -i -r / --exclude-dir=/sys --log=/var/log/clamav/clamAV.log
#- debug: var=backup_file

#- name: Add freshclam update marker
#  cron:
#    name: "ClamAV Update Syslog Event"
#    minute: "00"
#    hour: "22"
#    job: logger -i -t freshclam -p local2.info "Starting ClamAV signature updates"

- name: Add freshclam cron job
  cron:
    name: "ClamAV Signature Update"
    minute: "00"
    hour: "22"
    job: freshclam
  when: ansible_nodename != 'sec01.mgmt'
